// cd .\tempSeed\
// node .\seedTasks.js

// server/seedTasks.js
const Task = require("../models/tasks");
const mongoose = require("mongoose");
require("dotenv").config();

// Replace with your MongoDB connection string
const MONGODB_URI =
  "mongodb://localhost:27017/MMIN?readPreference=primary&appname=MongoDB%20Compass&ssl=false";

const sampleTasks = [
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how TrustyVest works.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "53 sec",
    rewardPercentage: 2,
    externalUrl: "https://youtu.be/Eiep-OuqYrA",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 2,
    displayDate: new Date("2025-08-18T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 53,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how TrustyVest works.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "53 sec",
    rewardPercentage: 2,
    externalUrl: "https://youtu.be/Eiep-OuqYrA",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 2,
    displayDate: new Date("2025-08-19T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 53,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how TrustyVest works.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "45 sec",
    rewardPercentage: 2,
    externalUrl: "https://youtu.be/suqvJH_cxpo",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 2,
    displayDate: new Date("2025-08-18T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 45,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how TrustyVest works.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "45 sec",
    rewardPercentage: 2,
    externalUrl: "https://youtu.be/suqvJH_cxpo",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 2,
    displayDate: new Date("2025-08-19T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 45,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how to complete tasks.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "22 sec",
    rewardPercentage: 2,
    externalUrl: "https://youtu.be/QQTdTgwR3dY",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 2,
    displayDate: new Date("2025-08-18T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 22,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how complete tasks.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "22 sec",
    rewardPercentage: 2,
    externalUrl: "https://youtu.be/QQTdTgwR3dY",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 2,
    displayDate: new Date("2025-08-19T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 22,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how to team up.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "41 sec",
    rewardPercentage: 2,
    externalUrl: "https://youtu.be/lCGLv8z2A9A",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 2,
    displayDate: new Date("2025-08-18T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 41,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how to team up.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "41 sec",
    rewardPercentage: 2,
    externalUrl: "https://youtu.be/lCGLv8z2A9A",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 2,
    displayDate: new Date("2025-08-19T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 41,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how to deposite.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "21 sec",
    rewardPercentage: 2,
    externalUrl: "https://youtu.be/a3z3KFKLfww",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 2,
    displayDate: new Date("2025-08-18T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 21,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how to deposite.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "21 sec",
    rewardPercentage: 2,
    externalUrl: "https://youtu.be/a3z3KFKLfww",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 2,
    displayDate: new Date("2025-08-19T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 21,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how TrustyVest works.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "53 sec",
    rewardPercentage: 3,
    externalUrl: "https://youtu.be/Eiep-OuqYrA",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 3,
    displayDate: new Date("2025-08-18T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 53,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how TrustyVest works.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "53 sec",
    rewardPercentage: 3,
    externalUrl: "https://youtu.be/Eiep-OuqYrA",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 3,
    displayDate: new Date("2025-08-19T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 53,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how TrustyVest works.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "45 sec",
    rewardPercentage: 3,
    externalUrl: "https://youtu.be/suqvJH_cxpo",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 3,
    displayDate: new Date("2025-08-18T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 45,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how TrustyVest works.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "45 sec",
    rewardPercentage: 3,
    externalUrl: "https://youtu.be/suqvJH_cxpo",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 3,
    displayDate: new Date("2025-08-19T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 45,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how to complete tasks.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "22 sec",
    rewardPercentage: 3,
    externalUrl: "https://youtu.be/QQTdTgwR3dY",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 3,
    displayDate: new Date("2025-08-18T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 22,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how complete tasks.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "22 sec",
    rewardPercentage: 3,
    externalUrl: "https://youtu.be/QQTdTgwR3dY",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 3,
    displayDate: new Date("2025-08-19T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 22,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how to team up.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "41 sec",
    rewardPercentage: 3,
    externalUrl: "https://youtu.be/lCGLv8z2A9A",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 3,
    displayDate: new Date("2025-08-18T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 41,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how to team up.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "41 sec",
    rewardPercentage: 3,
    externalUrl: "https://youtu.be/lCGLv8z2A9A",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 3,
    displayDate: new Date("2025-08-19T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 41,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how to deposite.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "21 sec",
    rewardPercentage: 3,
    externalUrl: "https://youtu.be/a3z3KFKLfww",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 3,
    displayDate: new Date("2025-08-18T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 21,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how to deposite.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "21 sec",
    rewardPercentage: 3,
    externalUrl: "https://youtu.be/a3z3KFKLfww",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 3,
    displayDate: new Date("2025-08-19T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 21,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how TrustyVest works.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "53 sec",
    rewardPercentage: 4,
    externalUrl: "https://youtu.be/Eiep-OuqYrA",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 4,
    displayDate: new Date("2025-08-18T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 53,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how TrustyVest works.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "53 sec",
    rewardPercentage: 4,
    externalUrl: "https://youtu.be/Eiep-OuqYrA",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 4,
    displayDate: new Date("2025-08-19T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 53,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how TrustyVest works.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "45 sec",
    rewardPercentage: 4,
    externalUrl: "https://youtu.be/suqvJH_cxpo",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 4,
    displayDate: new Date("2025-08-18T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 45,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how TrustyVest works.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "45 sec",
    rewardPercentage: 4,
    externalUrl: "https://youtu.be/suqvJH_cxpo",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 4,
    displayDate: new Date("2025-08-19T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 45,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how to complete tasks.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "22 sec",
    rewardPercentage: 4,
    externalUrl: "https://youtu.be/QQTdTgwR3dY",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 4,
    displayDate: new Date("2025-08-18T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 22,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how complete tasks.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "22 sec",
    rewardPercentage: 4,
    externalUrl: "https://youtu.be/QQTdTgwR3dY",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 4,
    displayDate: new Date("2025-08-19T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 22,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how to team up.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "41 sec",
    rewardPercentage: 4,
    externalUrl: "https://youtu.be/lCGLv8z2A9A",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 4,
    displayDate: new Date("2025-08-18T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 41,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how to team up.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "41 sec",
    rewardPercentage: 4,
    externalUrl: "https://youtu.be/lCGLv8z2A9A",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 4,
    displayDate: new Date("2025-08-19T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 41,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how to deposite.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "21 sec",
    rewardPercentage: 4,
    externalUrl: "https://youtu.be/a3z3KFKLfww",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 4,
    displayDate: new Date("2025-08-18T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 21,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how to deposite.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "21 sec",
    rewardPercentage: 4,
    externalUrl: "https://youtu.be/a3z3KFKLfww",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 4,
    displayDate: new Date("2025-08-19T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 21,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how TrustyVest works.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "53 sec",
    rewardPercentage: 0.5,
    externalUrl: "https://youtu.be/Eiep-OuqYrA",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 1,
    displayDate: new Date("2025-08-18T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 53,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how TrustyVest works.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "53 sec",
    rewardPercentage: 0.5,
    externalUrl: "https://youtu.be/Eiep-OuqYrA",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 1,
    displayDate: new Date("2025-08-19T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 53,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how TrustyVest works.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "45 sec",
    rewardPercentage: 0.5,
    externalUrl: "https://youtu.be/suqvJH_cxpo",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 1,
    displayDate: new Date("2025-08-18T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 45,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how TrustyVest works.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "45 sec",
    rewardPercentage: 0.5,
    externalUrl: "https://youtu.be/suqvJH_cxpo",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 1,
    displayDate: new Date("2025-08-19T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 45,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how to complete tasks.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "22 sec",
    rewardPercentage: 0.5,
    externalUrl: "https://youtu.be/QQTdTgwR3dY",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 1,
    displayDate: new Date("2025-08-18T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 22,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how complete tasks.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "22 sec",
    rewardPercentage: 0.5,
    externalUrl: "https://youtu.be/QQTdTgwR3dY",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 1,
    displayDate: new Date("2025-08-19T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 22,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how to team up.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "41 sec",
    rewardPercentage: 0.5,
    externalUrl: "https://youtu.be/lCGLv8z2A9A",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 1,
    displayDate: new Date("2025-08-18T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 41,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how to team up.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "41 sec",
    rewardPercentage: 0.5,
    externalUrl: "https://youtu.be/lCGLv8z2A9A",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 1,
    displayDate: new Date("2025-08-19T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 41,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how to deposite.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "21 sec",
    rewardPercentage: 0.5,
    externalUrl: "https://youtu.be/a3z3KFKLfww",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 1,
    displayDate: new Date("2025-08-18T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 21,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how to deposite.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "21 sec",
    rewardPercentage: 0.5,
    externalUrl: "https://youtu.be/a3z3KFKLfww",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 1,
    displayDate: new Date("2025-08-19T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 21,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
];

const seedTasks = async () => {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log("Connected to MongoDB");

    await Task.deleteMany({});
    console.log("Cleared existing tasks");

    const result = await Task.insertMany(sampleTasks);
    console.log(`Added ${result.length} sample tasks`);

    mongoose.connection.close();
    console.log("Database connection closed");
  } catch (error) {
    console.error("Error seeding tasks:", error);
    process.exit(1);
  }
};

seedTasks();
