// cd .\tempSeed\
// node .\seedTasks.js

// server/seedTasks.js
const Task = require("../models/tasks");
const mongoose = require("mongoose");
require("dotenv").config();

// Replace with your MongoDB connection string
const MONGODB_URI =
  "mongodb://localhost:27017/MMIN?readPreference=primary&appname=MongoDB%20Compass&ssl=false";

const sampleTasks = [
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how TrustyVest works.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "53 sec",
    rewardPercentage: 0.5,
    externalUrl: "https://youtu.be/Eiep-OuqYrA",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 1,
    displayDate: new Date("2025-08-03T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 53,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Complete Action & Submit Screenshot",
    description:
      "Follow the task instructions carefully and complete the required action on the external site or app.\nTake a screenshot as proof and upload it below to receive your reward.",
    type: "screenshot",
    difficulty: "medium",
    estimatedTime: "3 min",
    rewardPercentage: 0.5,
    externalUrl: "https://youtu.be/FAyKDaXEAgc",
    steps: [
      "Read the task details or open the provided link.",
      "Complete the required action (e.g., sign up, comment, like, share, etc.).",
      "Take a clear screenshot showing that you completed the task.",
      "Upload the screenshot using the Upload Proof button below.",
      "Click Submit Task to send it for review.",
      "Your reward will be added to your wallet after verification by our team.",
    ],
    active: true,
    minLevel: 1,
    displayDate: new Date("2025-08-03T00:00:00Z"),
    screenshotRequired: true,
    screenshotInstructions:
      "Make sure the screenshot clearly shows task completion.\nBlurry, incomplete, or unrelated screenshots may be rejected.\nVerification usually takes a few hours.",
    autoVerify: false,
    videoDuration: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how TrustyVest works.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "53 sec",
    rewardPercentage: 0.5,
    externalUrl: "https://youtu.be/Eiep-OuqYrA",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 1,
    displayDate: new Date("2025-08-03T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 53,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Complete Action & Submit Screenshot",
    description:
      "Follow the task instructions carefully and complete the required action on the external site or app.\nTake a screenshot as proof and upload it below to receive your reward.",
    type: "screenshot",
    difficulty: "medium",
    estimatedTime: "3 min",
    rewardPercentage: 0.5,
    externalUrl: "https://youtu.be/FAyKDaXEAgc",
    steps: [
      "Read the task details or open the provided link.",
      "Complete the required action (e.g., sign up, comment, like, share, etc.).",
      "Take a clear screenshot showing that you completed the task.",
      "Upload the screenshot using the Upload Proof button below.",
      "Click Submit Task to send it for review.",
      "Your reward will be added to your wallet after verification by our team.",
    ],
    active: true,
    minLevel: 1,
    displayDate: new Date("2025-08-03T00:00:00Z"),
    screenshotRequired: true,
    screenshotInstructions:
      "Make sure the screenshot clearly shows task completion.\nBlurry, incomplete, or unrelated screenshots may be rejected.\nVerification usually takes a few hours.",
    autoVerify: false,
    videoDuration: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how TrustyVest works.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "53 sec",
    rewardPercentage: 0.5,
    externalUrl: "https://youtu.be/Eiep-OuqYrA",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 1,
    displayDate: new Date("2025-08-03T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 53,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how TrustyVest works.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "53 sec",
    rewardPercentage: 0.5,
    externalUrl: "https://youtu.be/Eiep-OuqYrA",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 2,
    displayDate: new Date("2025-08-03T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 53,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Complete Action & Submit Screenshot",
    description:
      "Follow the task instructions carefully and complete the required action on the external site or app.\nTake a screenshot as proof and upload it below to receive your reward.",
    type: "screenshot",
    difficulty: "medium",
    estimatedTime: "3 min",
    rewardPercentage: 0.5,
    externalUrl: "https://youtu.be/FAyKDaXEAgc",
    steps: [
      "Read the task details or open the provided link.",
      "Complete the required action (e.g., sign up, comment, like, share, etc.).",
      "Take a clear screenshot showing that you completed the task.",
      "Upload the screenshot using the Upload Proof button below.",
      "Click Submit Task to send it for review.",
      "Your reward will be added to your wallet after verification by our team.",
    ],
    active: true,
    minLevel: 2,
    displayDate: new Date("2025-08-03T00:00:00Z"),
    screenshotRequired: true,
    screenshotInstructions:
      "Make sure the screenshot clearly shows task completion.\nBlurry, incomplete, or unrelated screenshots may be rejected.\nVerification usually takes a few hours.",
    autoVerify: false,
    videoDuration: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how TrustyVest works.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "53 sec",
    rewardPercentage: 0.5,
    externalUrl: "https://youtu.be/Eiep-OuqYrA",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 2,
    displayDate: new Date("2025-08-03T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 53,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Complete Action & Submit Screenshot",
    description:
      "Follow the task instructions carefully and complete the required action on the external site or app.\nTake a screenshot as proof and upload it below to receive your reward.",
    type: "screenshot",
    difficulty: "medium",
    estimatedTime: "3 min",
    rewardPercentage: 0.5,
    externalUrl: "https://youtu.be/FAyKDaXEAgc",
    steps: [
      "Read the task details or open the provided link.",
      "Complete the required action (e.g., sign up, comment, like, share, etc.).",
      "Take a clear screenshot showing that you completed the task.",
      "Upload the screenshot using the Upload Proof button below.",
      "Click Submit Task to send it for review.",
      "Your reward will be added to your wallet after verification by our team.",
    ],
    active: true,
    minLevel: 2,
    displayDate: new Date("2025-08-03T00:00:00Z"),
    screenshotRequired: true,
    screenshotInstructions:
      "Make sure the screenshot clearly shows task completion.\nBlurry, incomplete, or unrelated screenshots may be rejected.\nVerification usually takes a few hours.",
    autoVerify: false,
    videoDuration: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how TrustyVest works.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "53 sec",
    rewardPercentage: 0.5,
    externalUrl: "https://youtu.be/Eiep-OuqYrA",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 2,
    displayDate: new Date("2025-08-03T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 53,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how TrustyVest works.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "53 sec",
    rewardPercentage: 0.5,
    externalUrl: "https://youtu.be/Eiep-OuqYrA",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 3,
    displayDate: new Date("2025-08-03T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 53,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Complete Action & Submit Screenshot",
    description:
      "Follow the task instructions carefully and complete the required action on the external site or app.\nTake a screenshot as proof and upload it below to receive your reward.",
    type: "screenshot",
    difficulty: "medium",
    estimatedTime: "3 min",
    rewardPercentage: 0.5,
    externalUrl: "https://youtu.be/FAyKDaXEAgc",
    steps: [
      "Read the task details or open the provided link.",
      "Complete the required action (e.g., sign up, comment, like, share, etc.).",
      "Take a clear screenshot showing that you completed the task.",
      "Upload the screenshot using the Upload Proof button below.",
      "Click Submit Task to send it for review.",
      "Your reward will be added to your wallet after verification by our team.",
    ],
    active: true,
    minLevel: 3,
    displayDate: new Date("2025-08-03T00:00:00Z"),
    screenshotRequired: true,
    screenshotInstructions:
      "Make sure the screenshot clearly shows task completion.\nBlurry, incomplete, or unrelated screenshots may be rejected.\nVerification usually takes a few hours.",
    autoVerify: false,
    videoDuration: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how TrustyVest works.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "53 sec",
    rewardPercentage: 0.5,
    externalUrl: "https://youtu.be/Eiep-OuqYrA",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 3,
    displayDate: new Date("2025-08-03T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 53,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Complete Action & Submit Screenshot",
    description:
      "Follow the task instructions carefully and complete the required action on the external site or app.\nTake a screenshot as proof and upload it below to receive your reward.",
    type: "screenshot",
    difficulty: "medium",
    estimatedTime: "3 min",
    rewardPercentage: 0.5,
    externalUrl: "https://youtu.be/FAyKDaXEAgc",
    steps: [
      "Read the task details or open the provided link.",
      "Complete the required action (e.g., sign up, comment, like, share, etc.).",
      "Take a clear screenshot showing that you completed the task.",
      "Upload the screenshot using the Upload Proof button below.",
      "Click Submit Task to send it for review.",
      "Your reward will be added to your wallet after verification by our team.",
    ],
    active: true,
    minLevel: 3,
    displayDate: new Date("2025-08-03T00:00:00Z"),
    screenshotRequired: true,
    screenshotInstructions:
      "Make sure the screenshot clearly shows task completion.\nBlurry, incomplete, or unrelated screenshots may be rejected.\nVerification usually takes a few hours.",
    autoVerify: false,
    videoDuration: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how TrustyVest works.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "53 sec",
    rewardPercentage: 0.5,
    externalUrl: "https://youtu.be/Eiep-OuqYrA",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 3,
    displayDate: new Date("2025-08-03T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 53,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how TrustyVest works.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "53 sec",
    rewardPercentage: 0.5,
    externalUrl: "https://youtu.be/Eiep-OuqYrA",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 4,
    displayDate: new Date("2025-08-03T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 53,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Complete Action & Submit Screenshot",
    description:
      "Follow the task instructions carefully and complete the required action on the external site or app.\nTake a screenshot as proof and upload it below to receive your reward.",
    type: "screenshot",
    difficulty: "medium",
    estimatedTime: "3 min",
    rewardPercentage: 0.5,
    externalUrl: "https://youtu.be/FAyKDaXEAgc",
    steps: [
      "Read the task details or open the provided link.",
      "Complete the required action (e.g., sign up, comment, like, share, etc.).",
      "Take a clear screenshot showing that you completed the task.",
      "Upload the screenshot using the Upload Proof button below.",
      "Click Submit Task to send it for review.",
      "Your reward will be added to your wallet after verification by our team.",
    ],
    active: true,
    minLevel: 4,
    displayDate: new Date("2025-08-03T00:00:00Z"),
    screenshotRequired: true,
    screenshotInstructions:
      "Make sure the screenshot clearly shows task completion.\nBlurry, incomplete, or unrelated screenshots may be rejected.\nVerification usually takes a few hours.",
    autoVerify: false,
    videoDuration: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how TrustyVest works.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "53 sec",
    rewardPercentage: 0.5,
    externalUrl: "https://youtu.be/Eiep-OuqYrA",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 4,
    displayDate: new Date("2025-08-03T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 53,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Complete Action & Submit Screenshot",
    description:
      "Follow the task instructions carefully and complete the required action on the external site or app.\nTake a screenshot as proof and upload it below to receive your reward.",
    type: "screenshot",
    difficulty: "medium",
    estimatedTime: "3 min",
    rewardPercentage: 0.5,
    externalUrl: "https://youtu.be/FAyKDaXEAgc",
    steps: [
      "Read the task details or open the provided link.",
      "Complete the required action (e.g., sign up, comment, like, share, etc.).",
      "Take a clear screenshot showing that you completed the task.",
      "Upload the screenshot using the Upload Proof button below.",
      "Click Submit Task to send it for review.",
      "Your reward will be added to your wallet after verification by our team.",
    ],
    active: true,
    minLevel: 4,
    displayDate: new Date("2025-08-03T00:00:00Z"),
    screenshotRequired: true,
    screenshotInstructions:
      "Make sure the screenshot clearly shows task completion.\nBlurry, incomplete, or unrelated screenshots may be rejected.\nVerification usually takes a few hours.",
    autoVerify: false,
    videoDuration: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    title: "Watch the Video & Earn Instantly",
    description:
      "Watch the full YouTube video below to understand how TrustyVest works.\nComplete the viewing and click the Submit Task button to receive your reward.",
    type: "youtube_watch",
    difficulty: "easy",
    estimatedTime: "53 sec",
    rewardPercentage: 0.5,
    externalUrl: "https://youtu.be/Eiep-OuqYrA",
    steps: [
      "Click the Play button on the embedded video below.",
      "Watch the entire video without skipping.",
      "Once finished, scroll down and click the Submit Task button.",
      "Your reward will be instantly credited to your wallet.",
    ],
    active: true,
    minLevel: 4,
    displayDate: new Date("2025-08-03T00:00:00Z"),
    screenshotRequired: false,
    screenshotInstructions: "",
    autoVerify: true,
    videoDuration: 53,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
];

const seedTasks = async () => {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log("Connected to MongoDB");

    await Task.deleteMany({});
    console.log("Cleared existing tasks");

    const result = await Task.insertMany(sampleTasks);
    console.log(`Added ${result.length} sample tasks`);

    mongoose.connection.close();
    console.log("Database connection closed");
  } catch (error) {
    console.error("Error seeding tasks:", error);
    process.exit(1);
  }
};

seedTasks();
